[Link] Don't pre-fill email if it has logged out (#714)
* Add LinkSecureEmailStore, don't pre-fill email if email has logged out

* Use SHA256 instead of MD5

/Stripe/NSString+Stripe.swift:70:21: error: 'CC_MD5' was deprecated in Mac Catalyst 13.0: This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger).

* JSONEncoder/JSONDecoder, normalize emails

* Remove kSecAttrSynchronizable from email store

* Use base64EncodedString instead of constructing the string manually, use better key name

* Inject emailStore into PaymentSheetLinkAccount

* Delete email store in-favor of cookie store

* Clean up

* Use key for email storage

* Update mocks with hasEmailLoggedOut

* Delete before adding to ensure overwritten