Crypto Onramp SDK: Additional Auth APIs (#5203)
## Summary
Adds two additional auth-related APIs as documented
[here](https://docs.google.com/document/d/1fiRBeegAqMbaR7OUDUy0EA4idvHEDh_FcBE2DTz2vyo/edit?tab=t.0).

## Motivation
Required for the [Crypto Onramp
SDK](https://docs.google.com/document/d/1owKwHgD5s8u75EWDOny2bp6rlNZq1aI4NNUr43PKdVA/edit?tab=t.0#heading=h.5mbaom37vv77).

## Testing
I don’t have an example app ready yet, so I wired up a few calls to an
existing example UI and called the following from button actions.

```swift
do {
    let coordinator = try await CryptoOnrampCoordinator.create(apiClient: .shared, appearance: .init())
    try await coordinator.lookupConsumer(with: "michael@lickability.net")
    let authenticationResult = try await coordinator.presentForVerification(from: findViewController()!)
    print("Auth Result: \(authenticationResult)")
} catch {
    print("Error: \(error)")
}
```

**Success:**
```
[Stripe SDK]: POST "/v1/crypto/internal/customers" 200 req_exhqJjzpggKwz9
Auth Result: completed(customerId: "crc_1RnjGqLu5o3P18Zp6ihdypaQ")
```
**Canceled:**
```
Auth Result: canceled
```
**Re-ran with unregistered email:**
```
Error: noActiveLinkConsumer
```

```swift
do {
    let coordinator = try await CryptoOnrampCoordinator.create(apiClient: .shared, appearance: .init())
    try await coordinator.lookupConsumer(with: "mike@lickability.net")
    let id = try await coordinator.registerLinkUser(fullName: "Michael Liberatore", phone: "+13305555555", country: "US")
    print("Customer ID: \(id)")
} catch {
    print("Error: \(error)")
}
```

**Success**
```
[Stripe SDK]: POST "/v1/consumers/mobile/sign_up" 200 req_73mtNpnhfJl6WH
[Stripe SDK]: POST "/v1/crypto/internal/customers" 200 req_uO8TmAGvbadUvZ
Customer ID: crc_1RoA2DLu5o3P18ZpZte0on9V
```

**Re-ran with now-registered email:**
```
Error: An error occurred in PaymentSheet. Don't call sign up if not needed
```

## Changelog
N/A

---------

Co-authored-by: Mat Schmid <mats@stripe.com>