StripeCryptoOnramp: Additional Setup & Begins Public API (#5158)
## Summary
- Added remaining dependencies listed in the [Onramp tech spec under iOS
> SDK
Setup](https://docs.google.com/document/d/1owKwHgD5s8u75EWDOny2bp6rlNZq1aI4NNUr43PKdVA/edit?tab=t.0#heading=h.vqz32ccsplag)
to reduce noise in future PRs. Will remove any if we end up not using
them.
- Adds the very beginnings of the public API, which is still being
finalized in some aspects.
- Addresses the inability to pass in an `STPAPIClient` to
`LinkController`.

## Motivation

Necessary for the Crypto Onramp project.

Looking to keep moving forward and getting early feedback as I continue
coming up to speed. I thought opening small changes like this would give
a good opportunity for feedback, notes on approach, and the ability to
ask others questions regarding conventions.

## Testing
No tests yet. I tried the API out manually by wiring up a button to the
payment sheet example app. I navigated to another example first to
establish a test `publishableKey`.

```swift
@_spi(CryptoOnrampSDKPreview) import StripeCryptoOnramp

// …

Button("CryptoOnramp isLinkUser") {
    Task {
        do {
            let coordinator = try await CryptoOnrampCoordinator.create(apiClient: .shared, appearance: .init())
            let result1 = try await coordinator.isLinkUser(email: "michael@lickability.net")
            print("Result 1: \(result1)")
            
            let result2 = try await coordinator.isLinkUser(email: "michael@lickability.com")
            print("Result 2: \(result2)")
            
            let result3 = try await coordinator.isLinkUser(email: "michael")
            print("Result 3: \(result3)")
        } catch {
            print("Error: \(error)")
        }
    }
}
```

Here are the raw logs, annotated with comments prefixed by `#`.
```
[Stripe SDK]: POST "/v1/consumers/mobile/sessions/lookup" 200 req_bvC98S4NDmgQ6D
LOG ANALYTICS: link.account_lookup.complete - [(key: "pay_var", value: "paymentsheet"), (key: "ocr_type", value: "none"), (key: "lookupResult", value: "found"), (key: "apple_pay_enabled", value: 1)]

# Expected true (I signed up with this address)
Result 1: true

LOG ANALYTICS: stripeios.attest.assertion.failed - [(key: "error_type", value: "StripeCore.StripeAttest.AttestationError"), (key: "error_code", value: "attestationNotSupported")]
[Stripe SDK]: POST "/v1/consumers/mobile/sessions/lookup" 200 req_Js3HRaWFYbqNak
LOG ANALYTICS: link.account_lookup.complete - [(key: "pay_var", value: "paymentsheet"), (key: "ocr_type", value: "none"), (key: "lookupResult", value: "notFound"), (key: "apple_pay_enabled", value: 1)]

# Expected false (I’ve never signed up)
Result 2: false

LOG ANALYTICS: stripeios.attest.assertion.failed - [(key: "error_type", value: "StripeCore.StripeAttest.AttestationError"), (key: "error_code", value: "attestationNotSupported")]
[Stripe SDK]: POST "/v1/consumers/mobile/sessions/lookup" 400 req_m7G0msGkl0sWPk
LOG ANALYTICS: link.account_lookup.failure - [(key: "request_id", value: "req_m7G0msGkl0sWPk"), (key: "pay_var", value: "paymentsheet"), (key: "ocr_type", value: "none"), (key: "error_type", value: "invalid_request_error"), (key: "error_code", value: "email_invalid"), (key: "apple_pay_enabled", value: 1)]

# Expected error (bad input)
Error: apiError(StripeCore.StripeAPIError(type: StripeCore.StripeAPIError.ErrorType.invalidRequestError, code: Optional("email_invalid"), docUrl: Optional(https://stripe.com/docs/error-codes/email-invalid), message: Optional("Invalid email address."), param: nil, statusCode: Optional(400), requestID: Optional("req_m7G0msGkl0sWPk"), _allResponseFieldsStorage: Optional(4 fields)))
```

## Changelog
<!-- Is this a notable change that affects users? If so, add a line to
`CHANGELOG.md` and prefix the line with one of the following:
    - [Added] for new features.
    - [Changed] for changes in existing functionality.
    - [Deprecated] for soon-to-be removed features.
    - [Removed] for now removed features.
    - [Fixed] for any bug fixes.
    - [Security] in case of vulnerabilities.
-->
N/A